version: '3.7'
networks:
  app:
    driver: bridge

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: muffin15
    volumes:
      - ./mongo-data:/data/db
    networks:
      - app

  api:
    container_name: api
    restart: unless-stopped
    build:
      context: ""
      dockerfile: Dockerfile
    ports:
      - "5555:5555"
    volumes:
      - "./api:/api"
    networks:
      - app